default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 10

development:
  <<: *default
  database: guclink_development
  username: guclink
  password: guclink
  min_messages: warning

test:
  <<: *default
  database: guclink_organizer_testing
  username: guclink
  password: guclink
  min_messages: warning

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
